Add removal of old logic to check for the applet path
qmk/homebrew-qmk pull request #26
Opened 2021-07-24 09:17 UTC by bobsoppe

## Description

The original logic was not removed without these changes, so it would always exit out with the reason it could not find the applet. These changes will remove that if statement so that the intended patch will work correctly.

2021-07-24 09:46 UTC, fauxpark requested changes

2021-07-24 09:46 UTC, fauxpark commented on Patch/mdloader-applet-path.patch
> +index cbffc63..d7b6cd7 100644
```suggestion
```

2021-07-24 09:46 UTC, fauxpark commented on Patch/mdloader-applet-path.patch
> +index 4321de2..59f81a3 100644
```suggestion
```

2021-07-24 09:46 UTC, fauxpark commented on Patch/mdloader-applet-path.patch
> +index 0bd8575..2d75d6b 100644
```suggestion
```

2021-07-24 10:02 UTC, fauxpark commented
Actually, I think this is the intended logic?

First we try `fopen()` to attempt opening the file in the current directory. If that does not work (`!fIn`), we compute the applet path, then call `fopen()` again with that path. If *that* doesn't work (`!fIn` again), we print the error message.

In effect, the change is:
```diff
--- a/mdloader_common.c
+++ b/mdloader_common.c
@@ -754,14 +760,21 @@ int main(int argc, char *argv[])
       
     printf("Applet file: %s\n", appletfname);
 
-    fIn = fopen(appletfname, "rb");
+    fIn = fopen(appletfpath, "rb"); // Try in CWD first
+    if (!fIn)
+    {
+        get_applet_path(appletfname, appletfpath); // If not in CWD, look in $PREFIX/share/mdloader
+        fIn = fopen(appletfpath, "rb");
+    }
     if (!fIn)
     {
         printf("Error: Could not open applet file: %s\n", appletfname);
```

2021-07-24 10:22 UTC, fauxpark commented
Okay, I think I see what your change does - it basically assumes that if the applet file is not in the CWD, then it *will* be in `$PREFIX/share/mdloader`. I'm not so sure this is a good assumption to make, although yeah, I guess if the applet is missing from that folder, something's pretty wrong. But it's probably better to keep the error message in that case instead of potentially crashing.

2021-07-26 19:37 UTC, bobsoppe commented
Let's forget this PR 😂 I am not even sure what I thought that I wanted to fix here....
Things I learned, not to try to fix stuff in a project you do not know when it is already late
Sorry for bothering

2021-07-26 19:37 UTC, closed without merging